#!/usr/bin/env bash
#
# 🌾 SweetGrass: PROV-O Export Demo
# Time: ~10 minutes
# Shows: W3C PROV-O standards compliance
#

set -euo pipefail

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
OUTPUT_DIR="$SCRIPT_DIR/outputs/demo-$(date +%s)"
mkdir -p "$OUTPUT_DIR"

echo ""
echo "🌾 SweetGrass: PROV-O Export Demo"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "This demo shows W3C PROV-O standards compliance."
echo ""
sleep 2

# Start service
echo -e "${BLUE}Starting SweetGrass...${NC}"
cd "$PROJECT_ROOT"
RUST_LOG=error "$PROJECT_ROOT/target/release/sweetgrass" \
    --port 8080 --storage memory > "$OUTPUT_DIR/sweetgrass.log" 2>&1 &
SWEETGRASS_PID=$!

for i in {1..30}; do
    if curl -s http://localhost:8080/health > /dev/null 2>&1; then break; fi
    sleep 0.5
done
echo "   ✅ Service ready"
echo ""

# Create a research dataset Braid
echo -e "${BLUE}Step 1: Creating research dataset Braid...${NC}"
echo ""

BRAID_RESPONSE=$(curl -s -X POST http://localhost:8080/api/v1/braids \
    -H "Content-Type: application/json" \
    -d '{
      "data_hash": "sha256:research_dataset_v1_abc123def456",
      "mime_type": "application/x-hdf5",
      "size": 524288000,
      "was_attributed_to": [
        {"did": "did:key:z6MkAlice", "role": "Creator"},
        {"did": "did:key:z6MkBob", "role": "Contributor"}
      ],
      "was_generated_by": {
        "type": "DataCollection",
        "name": "Medical Imaging Collection",
        "started_at": "2025-01-01T00:00:00Z",
        "ended_at": "2025-06-30T23:59:59Z"
      },
      "tags": ["research", "medical", "imaging"]
    }')

BRAID_ID=$(echo "$BRAID_RESPONSE" | jq -r '.id')
echo "   ✅ Research dataset Braid created"
echo "   📦 ID: $BRAID_ID"
echo ""
sleep 2

# Export to PROV-O
echo -e "${BLUE}Step 2: Exporting to PROV-O JSON-LD...${NC}"
echo ""
echo "   PROV-O is the W3C standard for provenance ontology."
echo "   JSON-LD provides linked data semantics."
echo ""
sleep 2

PROVO_EXPORT=$(curl -s "http://localhost:8080/api/v1/provenance/$BRAID_ID")
echo "$PROVO_EXPORT" > "$OUTPUT_DIR/provo-export.jsonld"

echo "   ✅ PROV-O export complete"
echo ""
echo "   📄 Preview of exported structure:"
echo ""
echo "$PROVO_EXPORT" | jq '{
  "@context": .["@context"],
  "@type": .["@type"],
  "prov:wasAttributedTo": .["prov:wasAttributedTo"][0]["@id"],
  "prov:wasGeneratedBy": .["prov:wasGeneratedBy"]["@type"]
}' 2>/dev/null || echo "$PROVO_EXPORT" | head -30
echo ""
sleep 2

# Show W3C PROV-O structure
echo -e "${BLUE}Step 3: W3C PROV-O structure explained...${NC}"
echo ""
echo "   PROV-O defines three core classes:"
echo ""
echo "   1. prov:Entity (what)"
echo "      • Represents the data"
echo "      • Content-addressable (data_hash)"
echo "      • Example: Our research dataset"
echo ""
echo "   2. prov:Activity (how)"
echo "      • Represents the process"
echo "      • Time-bounded (start/end)"
echo "      • Example: Data collection activity"
echo ""
echo "   3. prov:Agent (who)"
echo "      • Represents actors"
echo "      • People, software, organizations"
echo "      • Example: Alice (Creator), Bob (Contributor)"
echo ""
sleep 3

# Show relationships
echo -e "${BLUE}Step 4: PROV-O relationships...${NC}"
echo ""
echo "   Key PROV-O properties:"
echo ""
echo "   • wasAttributedTo: Entity → Agent"
echo "     'The dataset was attributed to Alice'"
echo ""
echo "   • wasGeneratedBy: Entity → Activity"
echo "     'The dataset was generated by collection activity'"
echo ""
echo "   • wasAssociatedWith: Activity → Agent"
echo "     'The collection was associated with Alice'"
echo ""
echo "   • wasStartedBy: Activity → Agent"
echo "     'The collection was started by Alice'"
echo ""
sleep 3

# Interoperability
echo -e "${BLUE}Step 5: Interoperability benefits...${NC}"
echo ""
echo "   🌐 Standards compliance means:"
echo ""
echo "   1. Any PROV-O tool can read SweetGrass data"
echo "      • Python: prov library"
echo "      • JavaScript: prov.js"
echo "      • RDF triple stores"
echo ""
echo "   2. SweetGrass can import PROV-O from other systems"
echo "      • Research data repositories"
echo "      • Scientific workflow systems"
echo "      • Enterprise data catalogs"
echo ""
echo "   3. Semantic web integration"
echo "      • Link to other ontologies (FOAF, Dublin Core)"
echo "      • SPARQL queries"
echo "      • Knowledge graphs"
echo ""
sleep 3

# Validation
echo -e "${BLUE}Step 6: Validating PROV-O export...${NC}"
echo ""
echo "   Checking for required PROV-O elements..."
echo ""

HAS_CONTEXT=$(echo "$PROVO_EXPORT" | jq 'has("@context")' 2>/dev/null || echo "false")
HAS_TYPE=$(echo "$PROVO_EXPORT" | jq 'has("@type")' 2>/dev/null || echo "false")
HAS_ID=$(echo "$PROVO_EXPORT" | jq 'has("@id")' 2>/dev/null || echo "false")

echo "   JSON-LD @context: $([ "$HAS_CONTEXT" = "true" ] && echo '✅' || echo '❌')"
echo "   PROV-O @type: $([ "$HAS_TYPE" = "true" ] && echo '✅' || echo '❌')"
echo "   Unique @id: $([ "$HAS_ID" = "true" ] && echo '✅' || echo '❌')"
echo ""
echo "   $([ "$HAS_CONTEXT" = "true" ] && [ "$HAS_TYPE" = "true" ] && [ "$HAS_ID" = "true" ] && echo '✅ Valid PROV-O JSON-LD document' || echo '⚠️  Some elements missing')"
echo ""
sleep 2

# Use case example
echo -e "${BLUE}Step 7: Real-world use case...${NC}"
echo ""
echo "   📚 Scenario: Publishing research data"
echo ""
echo "   1. Researcher creates dataset in SweetGrass"
echo "   2. Export to PROV-O JSON-LD"
echo "   3. Publish to data repository (Zenodo, Figshare)"
echo "   4. Other researchers can:"
echo "      • See complete provenance"
echo "      • Cite all contributors"
echo "      • Import into their tools"
echo "      • Validate data lineage"
echo ""
echo "   Result: Open, reproducible, interoperable science! 🔬"
echo ""
sleep 2

# Cleanup
kill $SWEETGRASS_PID 2>/dev/null || true
wait $SWEETGRASS_PID 2>/dev/null || true

echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✅ Demo Complete!${NC}"
echo ""
echo "🎓 What you learned:"
echo "   ✅ W3C PROV-O ontology structure"
echo "   ✅ JSON-LD linked data format"
echo "   ✅ PROV-O export from SweetGrass"
echo "   ✅ Interoperability benefits"
echo "   ✅ Real-world use cases"
echo ""
echo "💡 Why PROV-O matters:"
echo "   • Standard: Recognized by W3C"
echo "   • Interoperable: Works with any PROV-O tool"
echo "   • Semantic: Linked data semantics"
echo "   • Tooling: Extensive ecosystem"
echo "   • Trust: Industry-standard provenance"
echo ""
echo "📁 Output: $OUTPUT_DIR/"
echo "   provo-export.jsonld - Full PROV-O export"
echo ""
echo "🔍 Try importing into:"
echo "   • Python: pip install prov"
echo "   • RDF: Load into triple store"
echo "   • SPARQL: Query with semantic queries"
echo ""
echo "⏭️  Next: Learn about privacy controls"
echo "   cd ../05-privacy-controls && ./demo-privacy-levels.sh"
echo ""

